### ISSUE TITLE
Trying to change default sigma in gui

### ISSUE THREAD

**Issue by cmgodd** [mcgarrysd/vessel_metrics#2]
attempt with comma separation "
Traceback (most recent call last):
  File "/Users/carolyngoddard/Documents/vm/vessel_metrics/final_scripts/vm_UI.py", line 65, in <module>
    settings = vm.make_segmentation_settings(segmentation_settings)
  File "/Users/carolyngoddard/Documents/vm/vessel_metrics/final_scripts/vessel_metrics.py", line 1063, in make_segmentation_settings
    res = tuple(map(int, settings_dict['sigma2'].split(' ')))
ValueError: invalid literal for int() with base 10: '20,40,10' "

attempt with space separation "Traceback (most recent call last):
  File "/Users/carolyngoddard/Documents/vm/vessel_metrics/final_scripts/vm_UI.py", line 178, in <module>
    seg_list = vm.analyze_images(images_to_analyze, file_names, settings, output_path)
  File "/Users/carolyngoddard/Documents/vm/vessel_metrics/final_scripts/vessel_metrics.py", line 1226, in analyze_images
    seg = segment_with_settings(s,settings)
  File "/Users/carolyngoddard/Documents/vm/vessel_metrics/final_scripts/vessel_metrics.py", line 1093, in segment_with_settings
    seg = segment_image(im, filter = settings['filter'], sigma1 = settings['sigma1'], sigma2 = settings['sigma2'], hole_size = settings['hole size'], ditzle_size = settings['ditzle size'], preprocess = settings['preprocess'], multi_scale = settings['multi scale'])
  File "/Users/carolyngoddard/Documents/vm/vessel_metrics/final_scripts/vessel_metrics.py", line 39, in segment_image
    enh_sig2 = meijering(im, sigmas = sigma2, mode = 'reflect', black_ridges = False)
  File "/Users/carolyngoddard/anaconda3/envs/Vesm/lib/python3.10/site-packages/skimage/filters/ridges.py", line 161, in meijering
    eigvals = hessian_matrix_eigvals(hessian_matrix(
  File "/Users/carolyngoddard/anaconda3/envs/Vesm/lib/python3.10/site-packages/skimage/feature/corner.py", line 318, in hessian_matrix
    return _hessian_matrix_with_gaussian(image, sigma=sigma, mode=mode,
  File "/Users/carolyngoddard/anaconda3/envs/Vesm/lib/python3.10/site-packages/skimage/feature/corner.py", line 196, in _hessian_matrix_with_gaussian
    truncate = 8 if all(s > 1 for s in sigma) else 100
  File "/Users/carolyngoddard/anaconda3/envs/Vesm/lib/python3.10/site-packages/skimage/feature/corner.py", line 196, in <genexpr>
    truncate = 8 if all(s > 1 for s in sigma) else 100
TypeError: '>' not supported between instances of 'str' and 'int'. "

carolyngoddard@Carolyns-MacBook-Air final_scripts % conda list -n Vesm --show-channel-urls
# packages in environment at /Users/carolyngoddard/anaconda3/envs/Vesm:
#
# Name                    Version                   Build  Channel
aicsimageio               4.10.0             pyhd8ed1ab_1    conda-forge
aiohttp                   3.8.4           py310h2aa6e3c_1    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
aom                       3.5.0                h7ea286d_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
aws-c-auth                0.7.0                h4ac17b4_1    conda-forge
aws-c-cal                 0.6.0                h43a37b4_0    conda-forge
aws-c-common              0.8.23               hb547adb_0    conda-forge
aws-c-compression         0.2.17               h31a6291_1    conda-forge
aws-c-event-stream        0.3.1                h1e1aaf7_1    conda-forge
aws-c-http                0.7.10               h3107daf_3    conda-forge
aws-c-io                  0.13.28              hf096fb3_0    conda-forge
aws-c-mqtt                0.8.14               h567deb8_1    conda-forge
aws-c-s3                  0.3.13               hf0ec796_1    conda-forge
aws-c-sdkutils            0.1.11               h31a6291_1    conda-forge
aws-checksums             0.1.16               h31a6291_1    conda-forge
aws-crt-cpp               0.20.3               hc3a2d08_3    conda-forge
aws-sdk-cpp               1.10.57             h6f3a27c_17    conda-forge
blosc                     1.21.4               hc338f07_0    conda-forge
bokeh                     3.2.0              pyhd8ed1ab_0    conda-forge
bresenham                 0.2.1                    pypi_0    pypi
brotli                    1.0.9                h1a8c8d9_9    conda-forge
brotli-bin                1.0.9                h1a8c8d9_9    conda-forge
brotli-python             1.0.9           py310h0f1eb42_9    conda-forge
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
c-blosc2                  2.10.0               h068da5f_0    conda-forge
ca-certificates           2023.5.7             hf0a4a13_0    conda-forge
cairo                     1.16.0            h1e71087_1016    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cfitsio                   4.2.0                h2f961c4_0    conda-forge
charls                    2.4.2                h13dd4ca_0    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.4           unix_pyh707e725_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0           py310h38f39d4_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0          py310h8e9501a_1    conda-forge
czifile                   2019.7.2           pyh9f0ad1d_0    conda-forge
dask                      2023.7.0           pyhd8ed1ab_0    conda-forge
dask-core                 2023.7.0           pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hb547adb_0    conda-forge
distributed               2023.7.0           pyhd8ed1ab_0    conda-forge
easygui                   0.98.3                   pypi_0    pypi
elementpath               2.5.3              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
ffmpeg                    6.0.0           gpl_h474fd3e_103    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.40.0          py310h2aa6e3c_0    conda-forge
freetype                  2.12.1               hd633e50_1    conda-forge
fribidi                   1.0.10               h27ca646_0    conda-forge
frozenlist                1.3.3           py310h8e9501a_0    conda-forge
fsspec                    2023.6.0           pyh1a96a4e_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
gflags                    2.2.2             hc88da5d_1004    conda-forge
giflib                    5.2.1                h1a8c8d9_3    conda-forge
glog                      0.6.0                h6da1cb0_0    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gnutls                    3.7.8                h9f1a10d_0    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
harfbuzz                  7.3.0                h46e5fef_0    conda-forge
hdf5                      1.14.1          nompi_h3aba7b3_100    conda-forge
icu                       72.1                 he12128b_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2023.1.23       py310hcb660b6_2    conda-forge
imagecodecs-lite          2019.12.3       py310hf1a086a_6    conda-forge
imageio                   2.31.1             pyh24c5eb1_0    conda-forge
imageio-ffmpeg            0.4.8              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
jasper                    4.0.0                hff9eb24_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jxrlib                    1.1                  h27ca646_2    conda-forge
kiwisolver                1.4.4           py310h2887b22_1    conda-forge
krb5                      1.20.1               h69eda48_0    conda-forge
lame                      3.100             h1a8c8d9_1003    conda-forge
lazy_loader               0.2                pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 hd835a16_1    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20230125.3      cxx17_h13dd4ca_0    conda-forge
libaec                    1.0.6                hb7217d7_1    conda-forge
libarrow                  12.0.1           h59b625a_3_cpu    conda-forge
libass                    0.17.1               h4da34ad_0    conda-forge
libavif                   0.11.1               h9f83d30_2    conda-forge
libblas                   3.9.0           17_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_9    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_9    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_9    conda-forge
libcblas                  3.9.0           17_osxarm64_openblas    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   8.1.2                h912dcd9_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.18                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libevent                  2.1.12               h2757513_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libglib                   2.76.4               h24e9cb9_0    conda-forge
libgoogle-cloud           2.12.0               he22f4c0_1    conda-forge
libgrpc                   1.54.2               h0a338ca_2    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libidn2                   2.3.4                h1a8c8d9_0    conda-forge
libjpeg-turbo             2.1.5.1              h1a8c8d9_0    conda-forge
liblapack                 3.9.0           17_osxarm64_openblas    conda-forge
liblapacke                3.9.0           17_osxarm64_openblas    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libopenblas               0.3.23          openmp_hc731615_0    conda-forge
libopencv                 4.7.0           py310hdc0018b_6    conda-forge
libopus                   1.3.1                h27ca646_1    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libprotobuf               3.21.12              hb5ab8b9_0    conda-forge
libsqlite                 3.42.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtasn1                  4.19.0               h1a8c8d9_0    conda-forge
libthrift                 0.18.1               ha061701_2    conda-forge
libtiff                   4.5.1                h23a1a89_0    conda-forge
libunistring              0.9.10               h3422bc3_0    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libvpx                    1.13.0               h7ea286d_0    conda-forge
libwebp-base              1.3.1                hb547adb_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.11.4               he3bdae6_0    conda-forge
libxslt                   1.1.37               h1728932_1    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
libzopfli                 1.0.3                h9f76cd9_0    conda-forge
llvm-openmp               16.0.6               h1c12783_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.3           py310h78afa71_0    conda-forge
lz4                       4.3.2           py310ha6df754_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
markupsafe                2.1.3           py310h2aa6e3c_0    conda-forge
matplotlib-base           3.7.2           py310h49faba3_0    conda-forge
more-itertools            9.1.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.5           py310h2887b22_0    conda-forge
multidict                 6.0.4           py310h8e9501a_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
nettle                    3.8.1                h63371fa_1    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numcodecs                 0.11.0          py310h0f1eb42_1    conda-forge
numpy                     1.25.1          py310haa1e00c_0    conda-forge
ome-types                 0.3.3              pyhd8ed1ab_0    conda-forge
ome-zarr                  0.8.0              pyhd8ed1ab_0    conda-forge
opencv                    4.7.0           py310hb6292c7_6    conda-forge
openh264                  2.3.1                hb7217d7_2    conda-forge
openjpeg                  2.5.0                hbc2ba62_2    conda-forge
openssl                   3.1.1                h53f4e23_1    conda-forge
orc                       1.9.0                ha98e9e8_1    conda-forge
p11-kit                   0.24.1               h29577a5_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3           py310h2b830bf_1    conda-forge
partd                     1.4.0              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
pickle5                   0.0.11                   pypi_0    pypi
pillow                    10.0.0          py310h60ecbdf_0    conda-forge
pint                      0.22               pyhd8ed1ab_1    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
platformdirs              3.8.1              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
psutil                    5.9.5           py310h8e9501a_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
py-opencv                 4.7.0           py310h69fb684_6    conda-forge
pyarrow                   12.0.1          py310hfbab16f_3_cpu    conda-forge
pydantic                  1.10.10         py310h2aa6e3c_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.12         h01493a6_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1           py310hf1a086a_0    conda-forge
pyyaml                    6.0             py310h8e9501a_5    conda-forge
re2                       2023.03.02           hc5e2d97_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
resource_backed_dask_array 0.1.0              pyhd8ed1ab_1    conda-forge
scikit-image              0.21.0          py310h1253130_0    conda-forge
scipy                     1.11.1          py310h0975f3d_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
svt-av1                   1.6.0                hb765f3a_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tifffile                  2023.2.28          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.2           py310h2aa6e3c_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
unicodedata2              15.0.0          py310h8e9501a_0    conda-forge
urllib3                   2.0.3              pyhd8ed1ab_1    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.15.0          py310h8e9501a_0    conda-forge
x264                      1!164.3095           h57fd34a_2    conda-forge
x265                      3.5                  hbc6ce65_3    conda-forge
xarray                    2023.1.0           pyhd8ed1ab_0    conda-forge
xmlschema                 1.11.3             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xyzservices               2023.5.0           pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yarl                      1.9.2           py310h2aa6e3c_0    conda-forge
zarr                      2.15.0             pyhd8ed1ab_0    conda-forge
zfp                       1.0.0                hb6e4faa_3    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.16.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zlib-ng                   2.0.7                h1a8c8d9_0    conda-forge
zstd                      1.5.2                h4f39d0f_7    conda-forge

**Comment by JoshuaShrouder** [comment]
Firstly, a potential wonderful piece of software, thank you very much for helping to improve the community of scientists working on vessel analysis. It is much appreciated, 

I have encountered exactly the same issues as cmgoddard, sigma input values of 1,6,1 1 6 1 or  (1,8,1) or 1,8,1. are not accepted for example, they will all give the same error message cmgoddard documented. Secondly, if the user is running the latest version of scikit-image, the script will not work at all, because of the deprecated compute_hessian_eigenvalues function since the latest scikit-image release, when converting the script to compute_hessian_eigenvals, to try and match the latest version (i did i with chat GPT) it also fails. so the only solution is reverting to an older version of scikit-image, I would think it best to adapt the script to match the latest version of scikit-image. While the sigma issue appears to be the main problem, many users trying to run the script for the first time will encounter the issue with scikit-image version, i think this should be addressed if you want lots of enthusiastic scientists to start using this pipeline (its a great idea). 

Lastly, tortuosity as a metric, is provided as somewhat of a low resolution, 0,1-1,0. I have adapted the script as follows to include a precision factor, which gives more granularity to the output def tortuosity(edge_labels, precision_factor=10):
    edges = np.zeros_like(edge_labels)
    edges[edge_labels > 0] = 1
    coords, end_points = find_endpoints(edges)
    endpoint_labeled = edge_labels * end_points
    unique_labels = np.unique(edge_labels)
    unique_labels = unique_labels[1:]
    tortuosity = []
    labels_used = []
    for u in unique_labels:
        this_segment = np.zeros_like(edge_labels)
        this_segment[edge_labels == u] = 1
        end_inds = np.argwhere(endpoint_labeled == u)
        if end_inds.size == 4:
            end_point_line = line(end_inds[0, 0], end_inds[0, 1], end_inds[1, 0], end_inds[1, 1])
            endpoint_distance = np.max(np.shape(end_point_line))
            segment_length = np.sum(this_segment)
            tortuosity_value = endpoint_distance / segment_length
            tortuosity_value *= precision_factor
            tortuosity.append(tortuosity_value)
            labels_used.append(u)
    return tortuosity, labels_used 

It is also worth noting that the script cant properly parse pathological twists and nicks in vessel straightness from naturally occuring physiological curves as it currently stands, once you breakdown the code, you will see it is using the endpoints and the segment length to give the tortuosity metric, but while one would expect curves in the physiological arrangement of the vasculature, sharp angles and kinks are generally a sign of pathology, which this tortuosity metric cannot distinguish effectively. Would be great to add a new portion of the script which uses the total deviation in FWHM along a segment length to assess the likelihood of whether a vessel was patent or not when perfused, or collapsed, as vessels which taper to a point are more than likely pathological in nature. One could use the standard deviation variance to determine this. 

My 2 cents as a researcher attempting to use this tool at the moment. A big congratulations to all authors, it is really very nice, but the functionality as it stands, needs a couple of minor alterations to reach its full potential!
